const actionsTypes = {
  PRODUCTS_FETCH_SUCESS: "PRODUCTS_FETCH_SUCESS",
  PRODUCTS_FETCH_LOADING: "PRODUCTS_FETCH_LOADING",
  PRODUCTS_FETCH_ERROR: "PRODUCTS_FETCH_ERROR",
  PRODUCTS_FILTER_BY_NAME: "PRODUCTS_FILTER_BY_NAME",
  PRODUCTS_CHANGE_SEARCH_NAME: "PRODUCTS_CHANGE_SEARCH_NAME",
  PRODUCTS_SELECTED_SIZE: "PRODUCTS_SELECTED_SIZE",
  SHOW_ADD_CART_ALERT: "SHOW_ADD_CART_ALERT",
  HIDE_ADD_CART_ALERT: "HIDE_ADD_CART_ALERT",
};

export { actionsTypes };
